### ISSUE TITLE
Is Avro to Json needed?

### ISSUE THREAD

**Issue by shnplr** [piotrsmolinski/avro-json#1]
Hi,
Thank-you for this very useful code :)

When is it preferable to use Avro2Json over GenericData.toString() - as both seem to render plain JSON (not JSON encoded AVRO)?

Cheers,
Paul

**Comment by shnplr** [comment]
GenericData.toString() should not be used with the expectation it will produce value JSON, in other words output of toString should not be parsed as JSON.

**Comment by piotrsmolinski** [comment]
This code solves the problem of the Avro built-in JSON support, specifically handling of the optional fields. In Avro optional field is a union of **null** and actual type (like **string**).
The expected JSON in this case is:
```
{
  "key": "value"
}
```
From JSON datum encoder we get:
```
{
  "key": {
    "string": "value"
  }
}
```
The same applies the opposite way, i.e. the first form won't be parsed using JSON datum decoder.
The canonical way of rendering the JSON from Avro is:
```
ByteArrayOutputStream baos = new ByteArrayOutputStream();
Encoder encoder = EncoderFactory.get().jsonEncoder(schema, baos, true);
DatumWriter<Object> writer = GenericData.get().createDatumWriter(schema);
writer.write(avro, encoder);
encoder.flush();
String json = new String(baos.toByteArray(), StandardCharsets.UTF_8);
```
This guarantees to produce a valid JSON. The problem is that the result is still Avro, only encoded as text.
